// AI工具数据库
export const categories = [
  { id: 'writing', name: 'AI写作', icon: '✍️', count: 8 },
  { id: 'image', name: 'AI绘画', icon: '🎨', count: 6 },
  { id: 'video', name: 'AI视频', icon: '🎬', count: 5 },
  { id: 'code', name: 'AI编程', icon: '💻', count: 5 },
  { id: 'office', name: 'AI办公', icon: '📊', count: 5 },
  { id: 'marketing', name: 'AI营销', icon: '📈', count: 4 },
  { id: 'chat', name: 'AI对话', icon: '💬', count: 4 },
  { id: 'search', name: 'AI搜索', icon: '🔍', count: 4 },
  { id: 'audio', name: 'AI音频', icon: '🎵', count: 3 },
  { id: 'design', name: 'AI设计', icon: '🎯', count: 3 },
];

export const tools = [
  // AI写作
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    category: 'writing',
    icon: '🤖',
    tagline: 'OpenAI出品的AI对话写作助手，全球最流行的AI工具',
    description: 'ChatGPT是OpenAI推出的AI聊天助手，支持多轮对话、文本生成、代码编写、翻译等多种任务。GPT-4o模型具备强大的理解和创作能力，是目前使用最广泛的AI工具。',
    features: ['多轮对话', '文章写作', '代码生成', '文件上传分析', '图片生成(DALL-E)', '联网搜索'],
    pricing: { free: true, price: '免费可用', paid: '$20/月(Plus)' },
    scores: { usefulness: 95, value: 90, ease: 95 },
    pros: ['能力全面，几乎什么都能做', '生态丰富，插件/自定义GPT', '免费版够日常使用'],
    cons: ['Plus价格对国内用户偏贵', '高峰期免费版可能限流', '中文长文创作偶尔重复'],
    affiliate: null,
    url: 'https://chat.openai.com',
    updatedAt: '2026-04-20',
  },
  {
    id: 'claude',
    name: 'Claude',
    category: 'writing',
    icon: '🟠',
    tagline: 'Anthropic出品，长文本处理和深度写作的最佳选择',
    description: 'Claude是Anthropic推出的AI助手，以超长上下文窗口（200K tokens）和高质量长文输出著称。在论文写作、文档分析、代码审查等场景表现突出。',
    features: ['200K超长上下文', '高质量长文写作', '代码分析', '文档对比', 'Artifacts实时预览'],
    pricing: { free: true, price: '免费可用', paid: '$20/月(Pro)' },
    scores: { usefulness: 92, value: 88, ease: 93 },
    pros: ['长文质量极高，逻辑连贯', '200K上下文，一次吃下一本书', '安全性设计好'],
    cons: ['国内访问需要梯子', '图片生成能力不如GPT', '免费版额度较少'],
    affiliate: null,
    url: 'https://claude.ai',
    updatedAt: '2026-04-20',
  },
  {
    id: 'kimi',
    name: 'Kimi',
    category: 'writing',
    icon: '🌙',
    tagline: '月之暗面出品，国内最好用的长文本AI助手',
    description: 'Kimi是月之暗面推出的AI助手，支持200万字超长上下文，特别擅长文档阅读、论文总结、长文创作。国内直连，无需梯子，中文体验优秀。',
    features: ['200万字超长上下文', '文件/网页阅读', '中文长文创作', '联网搜索', '多格式文件支持'],
    pricing: { free: true, price: '完全免费', paid: null },
    scores: { usefulness: 88, value: 98, ease: 95 },
    pros: ['完全免费，国内良心产品', '中文长文质量很高', '无需梯子，直连使用'],
    cons: ['英文能力不如GPT/Claude', '代码能力一般', '图片理解有限'],
    affiliate: null,
    url: 'https://kimi.moonshot.cn',
    updatedAt: '2026-04-20',
  },
  {
    id: 'tongyi',
    name: '通义千问',
    category: 'writing',
    icon: '🔵',
    tagline: '阿里出品，全能型AI助手+免费API',
    description: '通义千问是阿里巴巴推出的大语言模型产品，支持对话、写作、代码、图片生成等。其API免费额度高达100万tokens，是开发者最爱。',
    features: ['多轮对话', 'AI绘画(通义万相)', '代码助手', '文档阅读', '免费API 100万tokens'],
    pricing: { free: true, price: '免费可用', paid: null },
    scores: { usefulness: 85, value: 96, ease: 90 },
    pros: ['API免费额度极大', '国内生态整合好(钉钉等)', '多模态能力全'],
    cons: ['创意写作不如Claude', '偶有政治敏感过滤', '界面不如竞品精致'],
    affiliate: null,
    url: 'https://tongyi.aliyun.com',
    updatedAt: '2026-04-20',
  },
  {
    id: 'doubao',
    name: '豆包',
    category: 'writing',
    icon: '🟣',
    tagline: '字节跳动出品，免费全能AI助手',
    description: '豆包是字节跳动推出的AI助手，完全免费，支持对话、写作、翻译、图片生成等。与抖音生态打通，擅长短视频脚本和社交文案。',
    features: ['智能对话', '图片生成', '短视频脚本', '社交文案', '浏览器插件'],
    pricing: { free: true, price: '完全免费', paid: null },
    scores: { usefulness: 82, value: 98, ease: 95 },
    pros: ['完全免费无限制', '短视频/小红书文案强', '手机App体验好'],
    cons: ['深度分析能力弱', 'API暂不开放', '知识面不如GPT广'],
    affiliate: null,
    url: 'https://www.doubao.com',
    updatedAt: '2026-04-20',
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    category: 'writing',
    icon: '📝',
    tagline: '笔记+AI写作的最佳结合，办公写作利器',
    description: 'Notion AI将AI写作能力深度集成到Notion笔记中，支持在文档中直接AI续写、总结、翻译、改写。对于已经在用Notion的人是无缝体验。',
    features: ['AI续写/改写', '文档总结', '翻译', '头脑风暴', '表格填充', '项目管理AI'],
    pricing: { free: false, price: '$10/月起', paid: '$10/月' },
    scores: { usefulness: 86, value: 78, ease: 92 },
    pros: ['与Notion深度集成，无缝体验', '文档场景AI最好用', '改写/总结功能实用'],
    cons: ['需要Notion付费计划', '单独购买AI另加$10/月', '中文质量一般'],
    affiliate: 'https://ntn.so/aitools',
    updatedAt: '2026-04-20',
  },
  {
    id: 'youdao-ai',
    name: '有道AI写作',
    category: 'writing',
    icon: '📗',
    tagline: '网易出品，论文写作和翻译的专业工具',
    description: '有道AI写作专注学术和翻译场景，支持论文写作、润色、降重、翻译。与有道词典深度整合，英文写作场景特别好用。',
    features: ['论文写作', '论文降重', 'AI润色', '专业翻译', '语法检查'],
    pricing: { free: true, price: '免费体验', paid: '¥29/月' },
    scores: { usefulness: 80, value: 82, ease: 88 },
    pros: ['论文场景专业', '翻译质量高', '与有道词典联动'],
    cons: ['非论文场景一般', '免费额度很少', '创意写作弱'],
    affiliate: null,
    url: 'https://ai.youdao.com',
    updatedAt: '2026-04-20',
  },
  {
    id: 'bililing',
    name: '笔灵AI',
    category: 'writing',
    icon: '🖊️',
    tagline: '600+写作模板，国内最全的AI写作平台',
    description: '笔灵AI提供600+写作模板，覆盖论文、小说、公文、营销文案等多种场景。模板驱动，填关键词即可生成，适合不会写prompt的用户。',
    features: ['600+写作模板', '论文写作', '公文写作', '小说创作', '降重改写'],
    pricing: { free: true, price: '免费体验3篇', paid: '¥39/月' },
    scores: { usefulness: 78, value: 75, ease: 95 },
    pros: ['模板多，傻瓜式操作', '中文场景覆盖全', '上手零门槛'],
    cons: ['模板输出较模板化', '免费额度太少', '深度不如ChatGPT'],
    affiliate: null,
    url: 'https://ibiling.cn',
    updatedAt: '2026-04-20',
  },
  // AI绘画
  {
    id: 'midjourney',
    name: 'Midjourney',
    category: 'image',
    icon: '⛵',
    tagline: 'AI绘画天花板，艺术创作首选',
    description: 'Midjourney是目前公认AI绘画质量最高的工具，擅长写实照片、艺术插画、概念设计等。V6版本在细节和文字生成方面大幅提升。',
    features: ['高质量AI绘画', '照片级写实', '艺术风格多样', '文字渲染(V6)', '风格参考', '角色一致性'],
    pricing: { free: false, price: '$10/月起', paid: '$10-120/月' },
    scores: { usefulness: 95, value: 80, ease: 65 },
    pros: ['画质业界第一', '艺术表现力极强', '社区作品可参考'],
    cons: ['需Discord操作，门槛高', '没有免费版', '中文prompt效果差'],
    affiliate: null,
    url: 'https://www.midjourney.com',
    updatedAt: '2026-04-20',
  },
  {
    id: 'liblibai',
    name: 'LiblibAI·哩布哩布',
    category: 'image',
    icon: '🖼️',
    tagline: '国内最大AI绘画社区，免费在线生图',
    description: 'LiblibAI是国内领先的AI绘画平台，提供海量Stable Diffusion模型和在线生图功能。免费用户每天有生图额度，社区模型丰富。',
    features: ['在线Stable Diffusion', '海量模型下载', 'LoRA模型', '免费生图额度', '社区分享', 'ComfyUI工作流'],
    pricing: { free: true, price: '免费额度可用', paid: '¥30/月起' },
    scores: { usefulness: 88, value: 90, ease: 80 },
    pros: ['免费可用，模型超多', '国内直连速度快', '社区活跃作品多'],
    cons: ['画质不如Midjourney', '需要学prompt', '高级功能需付费'],
    affiliate: null,
    url: 'https://www.liblib.art',
    updatedAt: '2026-04-20',
  },
  {
    id: 'stable-diffusion',
    name: 'Stable Diffusion',
    category: 'image',
    icon: '🔥',
    tagline: '开源AI绘画之王，本地部署完全免费',
    description: 'Stable Diffusion是最流行的开源AI绘画模型，可以本地部署完全免费使用。ComfyUI/WebUI等前端工具强大，模型生态最丰富。',
    features: ['完全开源免费', '本地部署无限用', '丰富模型生态', 'ComfyUI工作流', 'ControlNet精准控制', '训练自定义模型'],
    pricing: { free: true, price: '完全免费', paid: null },
    scores: { usefulness: 92, value: 100, ease: 40 },
    pros: ['完全免费无限制', '自由度最高', '模型生态最丰富'],
    cons: ['需要显卡(6GB+)', '学习曲线很陡', '安装配置复杂'],
    affiliate: null,
    url: 'https://stability.ai',
    updatedAt: '2026-04-20',
  },
  {
    id: 'd-design',
    name: '堆友AI',
    category: 'image',
    icon: '🎨',
    tagline: '国内最好用的AI绘画和设计工具',
    description: '堆友AI是酷家乐推出的AI绘画和设计平台，支持文生图、图生图、AI海报、AI电商图等。中文prompt效果好，国内直连。',
    features: ['文生图/图生图', 'AI海报设计', '电商主图生成', '中文prompt优化', '模板库'],
    pricing: { free: true, price: '免费体验', paid: '¥29/月' },
    scores: { usefulness: 82, value: 80, ease: 88 },
    pros: ['中文prompt效果好', '电商场景实用', '上手简单'],
    cons: ['免费额度少', '画质不如MJ', '创意风格有限'],
    affiliate: null,
    url: 'https://d.design',
    updatedAt: '2026-04-20',
  },
  // AI视频
  {
    id: 'sora',
    name: 'Sora',
    category: 'video',
    icon: '🎬',
    tagline: 'OpenAI出品，AI视频生成最强',
    description: 'Sora是OpenAI推出的AI视频生成模型，支持文本生成高质量视频。画面质量、物理一致性和时长在AI视频领域处于领先地位。',
    features: ['文本生成视频', '图生视频', '视频延展', '最长60秒', '高质量物理模拟'],
    pricing: { free: false, price: '$20/月(ChatGPT Plus)', paid: '$20/月' },
    scores: { usefulness: 90, value: 75, ease: 85 },
    pros: ['画质业界顶级', '物理模拟真实', '与ChatGPT集成'],
    cons: ['生成速度慢', '需要Plus订阅', '国内需梯子'],
    affiliate: null,
    url: 'https://sora.com',
    updatedAt: '2026-04-20',
  },
  {
    id: 'kling',
    name: '可灵AI',
    category: 'video',
    icon: '🎞️',
    tagline: '快手出品，国内最强AI视频生成工具',
    description: '可灵AI是快手推出的AI视频生成平台，支持文生视频和图生视频，画质接近Sora水平。国内直连，免费用户每日有生成额度。',
    features: ['文生视频', '图生视频', '视频续写', '运动笔刷', 'AI特效'],
    pricing: { free: true, price: '每日免费额度', paid: '¥66/月' },
    scores: { usefulness: 88, value: 85, ease: 88 },
    pros: ['国内直连，速度快', '画质接近Sora', '免费额度够日常用'],
    cons: ['长视频一致性一般', '高峰期排队久', '专业版价格不低'],
    affiliate: null,
    url: 'https://kling.kuaishou.com',
    updatedAt: '2026-04-20',
  },
  // AI编程
  {
    id: 'cursor',
    name: 'Cursor',
    category: 'code',
    icon: '🖱️',
    tagline: 'AI编程IDE，Vibe Coding首选工具',
    description: 'Cursor是基于VS Code的AI编程IDE，支持AI对话式编程、代码自动补全、多文件编辑等。是Vibe Coding和AI辅助编程的首选工具。',
    features: ['AI对话编程', '智能代码补全', '多文件AI编辑', '代码库理解', 'Terminal AI', '支持多种AI模型'],
    pricing: { free: true, price: '免费2000次补全/月', paid: '$20/月' },
    scores: { usefulness: 95, value: 88, ease: 85 },
    pros: ['编程效率提升巨大', '免费版够轻度使用', 'VS Code用户无缝迁移'],
    cons: ['Pro版$20/月不便宜', '大型项目AI偶尔理解错', '需要联网'],
    affiliate: null,
    url: 'https://cursor.com',
    updatedAt: '2026-04-20',
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    category: 'code',
    icon: '🐙',
    tagline: 'AI代码补全鼻祖，开发者标配',
    description: 'GitHub Copilot是最早的AI编程助手，深度集成到VS Code/JetBrains等IDE，提供智能代码补全和建议。',
    features: ['智能代码补全', 'Chat模式', 'CLI助手', '多IDE支持', '企业版代码库理解'],
    pricing: { free: false, price: '$10/月', paid: '$10-39/月' },
    scores: { usefulness: 90, value: 82, ease: 90 },
    pros: ['补全质量高', 'IDE集成好', '学生免费'],
    cons: ['没有免费版(学生除外)', '对话能力不如Cursor', '企业版贵'],
    affiliate: null,
    url: 'https://github.com/features/copilot',
    updatedAt: '2026-04-20',
  },
  {
    id: 'trae',
    name: 'TRAE',
    category: 'code',
    icon: '⚡',
    tagline: '字节跳动出品的免费AI编程IDE',
    description: 'TRAE是字节跳动推出的AI编程IDE，基于VS Code，内置AI对话和代码生成。完全免费，支持Claude和GPT模型。',
    features: ['AI对话编程', '智能补全', 'Builder模式', '免费使用GPT/Claude', '中文支持好'],
    pricing: { free: true, price: '完全免费', paid: null },
    scores: { usefulness: 85, value: 100, ease: 82 },
    pros: ['完全免费', '内置GPT/Claude模型', '中文体验好'],
    cons: ['产品较新稳定性待验证', '社区生态不如Cursor', '插件兼容性偶有问题'],
    affiliate: null,
    url: 'https://www.trae.ai',
    updatedAt: '2026-04-20',
  },
  // AI办公
  {
    id: 'aippt',
    name: 'AiPPT',
    category: 'office',
    icon: '📊',
    tagline: 'AI一键生成高质量PPT，职场人必备',
    description: 'AiPPT可以输入主题一键生成完整PPT，支持多种模板风格、AI排版、内容填充。适合需要快速做PPT的职场场景。',
    features: ['一键生成PPT', 'AI排版美化', '多种模板', '内容AI填充', '大纲生成', 'Word转PPT'],
    pricing: { free: true, price: '免费3次', paid: '¥29/月' },
    scores: { usefulness: 82, value: 78, ease: 95 },
    pros: ['一键生成真的一键', '模板质量不错', '职场人刚需'],
    cons: ['免费次数太少', '复杂PPT还是需手动调', '创意设计类PPT一般'],
    affiliate: null,
    url: 'https://www.aippt.cn',
    updatedAt: '2026-04-20',
  },
  {
    id: 'metaso',
    name: '秘塔AI搜索',
    category: 'search',
    icon: '🔎',
    tagline: '最好用的AI搜索，没有广告直达结果',
    description: '秘塔AI搜索是国产AI搜索引擎，最大特点是没有广告、直达结构化结果。支持学术/研究/视频等多种搜索模式，信息溯源清晰。',
    features: ['无广告AI搜索', '结构化结果', '信息溯源', '学术模式', '研究模式', '思维导图生成'],
    pricing: { free: true, price: '免费可用', paid: '¥12/月' },
    scores: { usefulness: 90, value: 95, ease: 95 },
    pros: ['没广告，结果干净', '结构化展示很清晰', '免费版够用'],
    cons: ['实时信息偶有延迟', '深度分析不如Perplexity', '专业领域覆盖有限'],
    affiliate: null,
    url: 'https://metaso.cn',
    updatedAt: '2026-04-20',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    category: 'search',
    icon: '🟢',
    tagline: '全球最强AI搜索引擎，信息研究必备',
    description: 'Perplexity是全球最知名的AI搜索引擎，能联网搜索并给出带引用的AI回答。适合信息研究、事实核查、趋势分析等深度搜索场景。',
    features: ['AI搜索+引用', '联网实时搜索', '学术搜索', '文件上传分析', 'Focus模式', 'API'],
    pricing: { free: true, price: '免费5次/天', paid: '$20/月' },
    scores: { usefulness: 93, value: 80, ease: 90 },
    pros: ['引用溯源，结果可信', '搜索质量全球第一', '免费版够轻度用'],
    cons: ['免费版每天5次限制', '国内需梯子', 'Pro版$20/月不便宜'],
    affiliate: null,
    url: 'https://www.perplexity.ai',
    updatedAt: '2026-04-20',
  },
];

// 获取分类下的工具
export function getToolsByCategory(categoryId) {
  return tools.filter(t => t.category === categoryId);
}

// 获取工具详情
export function getToolBySlug(slug) {
  return tools.find(t => t.id === slug) || null;
}

// 获取评分标签
export function getScoreLabel(score) {
  if (score >= 90) return '优秀';
  if (score >= 80) return '良好';
  if (score >= 70) return '一般';
  return '待提升';
}

export function getScoreColor(score) {
  if (score >= 90) return '#4ecca3';
  if (score >= 80) return '#e9a545';
  if (score >= 70) return '#e94560';
  return '#888';
}
